{ +block{chinalist-lite} }
.16\.plwan\.com[/&:?=_]
.252d\.com[/&:?=_]
.6dvip\.com[/&:?=_]
.91339\.com[/&:?=_]
.cyacc\.com[/&:?=_]
.log\.hiiir\.com[/&:?=_]
.notice\.uchome\.manyou\.com[/&:?=_]
.shurumedia\.com[/&:?=_]
.sphwq\.net[/&:?=_]
.ttmsg\.qianqian\.com[/&:?=_]
.un\.5d6d\.com[/&:?=_]
.uu456\.com[/&:?=_]
.weddingeeos\.com[/&:?=_]
.xcy8\.com[/&:?=_]
.xinwenke\.com[/&:?=_]
/acmsd/.*
\.affiliate\.
\.cn/ads/
\.com\.cn/js/ad\.
\.com/js/ad\.
\.com/js/ads/
\.info/ad/
\.org/adv/
/adfiles/.*
/adflash/.*
/adimage/.*
/adjs/.*
/adphoto/.*
/adpics/.*
/adpolestar/.*
/adpshow\.
/adpuba/.*
/adservice/.*
/advpic/.*
/attachments/ad/.*
/data/ad/.*
/dkgg/.*
/duilian\.
/events/ad/.*
/floatad\.
/floatadv\.
/gaog/.*
/gg1\.
/gg2\.
/ggao\.
/ggao/.*
/ggjs/.*
/ggpic/.*
/guangao/.*
/guangg/.*
/guanggao\.
/guanggao/.*
/images/prom/.*
/main/s\?
/paypic/.*
/piaofu\.js
/pic/ad/.*
/picad/.*
/proxy\.htm\?id=
/proxy\.html\?id=
/tan\.js
/tan1\.js
/tanchuang\.
/tuiguang/.*
/u/_sponsor/.*
/webafp\?
/ysm\.ezprice\.net/.*
^http://.*\.cn/ad/
^http://.*\.hk/ad/
^http://.*/js/ad\.
^http://.*/js/ad/
^http://.*/js/tc\.js
^http://acs\.
^https://.*/ad/
.iapp\.com\.tw/iapp_ad\.php
.ruanyifeng\.com/blog/images/ad_
.btmee\.com/static/btmeegg/
.cnzz\.cn[/&:?=_].*zanzhu
.shooter\.cn/a/img/prom/
.vdisk\.cn/img/
.ngacn\.cc/common_res/js_adscommon\.js
.pic\.bahamut\.com\.tw/js/ad\.js
.hiad\.vmall\.com[/&:?=_]
.log\.vdisk\.cn[/&:?=_]
.static\.115img\.com/static/delivery/
.static\.colafile\.com/cola3/newdown/join\.png
.static\.colafile\.com/images/vip\.png
.job\.cnbeta\.com/jobs/
.newtalk\.tw/media/ad/
/configs/article/gggg/.*
.17dm\.com/s/common/js/.*AD\.js
.17kk\.cc/scriptAD/
.33xs\.com/hot/
.33xs\.com/js/mg
.35zww\.com/zzzjs/
.3yt\.com/2009js/
.52kdm\.com/javascript/show\.js
.52kdm\.com/s/
.77119\.com/js/
.9lala\.com/js/
.baishuzhai\.com/css/inend\.js
.bengou\.com/game/
.binhuo\.com/bhjs/
.booksky\.org/popa\.js
.boxiw\.com/js/
.bxs\.cc/888/
.cc222\.com/_javascript/popupWin\.js
.cc222\.com/cc222Ads/
.cococomic\.com/aitw/
.cococomic\.com/g/
.cococomic\.com/script/tjs\.js
.d3zw\.com/js/.*\.aspx
.dm8\.cc/javascript/xshow\.js
.dm8\.cc/s/
.dm8\.cc/show/
.dudu8\.net/a_d/
.dukankan\.com/xiaoyi/js/
.flux\.faloo\.com/pvdata\.aspx
.ggyy8\.cc/js/v/
.haoqi99\.com/js/fumeiti\.js
.hotsk\.com/js/asp\.js
.hszw\.com/inc/
.images\.xxsy\.net/js/xxsypop\.js
.images\.xxsy\.net/sygg/
.imanhua\.com[/&:?=_].*/money/
.imanhua\.com[/&:?=_].*/nmoneys/
.imghw\.3gsc\.com\.cn[/&:?=_]
.jj\.5ccc\.net/scripts/new/
.jpnovel\.com/myjs/
.js\.fengwu\.net/baidu/
.kukudm\.com/kukuad/
.laishu\.com/lsgg/
.niaoyan\.net/wlxsjs/c_gg2\.js
.niubb\.net/niubbad/
.quanben\.com/themes/quanben/qj\.js
.ranhen\.com/js/
.ranwen\.net/ssi/
.ruyu\.org/js/
.s\.faloo\.com/novel/ad\.js
.shuhe\.cc/ssi/
.shushuw\.cn/js/eteadx2011\.js
.site\.24novel\.com/js/readbottom\.js
.t\.33xs\.com/js/g
.t\.58xs\.com/hot/
.ttshu\.com/js/
.wandoou\.com/heibing/js/640X60\.js
.wcxiaoshuo\.com/js/
.xiaolushu\.com/js/
.xiaoxiucai\.org/configs/mu-2\.js
.xiazailou\.com/js/new/read01\.js
.xizibook\.com/js_ad/
.xkzw\.org/wlxsjs/
.xs8\.cn/data/iframe/xs8_text_title\.js
.xs8\.cn/xs8_stat\.js
.xskz\.com/js/kz\.js
.xzcl\.com/top/
.zzzcn\.com/3z/
shumilou\.com/style/aadd\.js
.abc\.hkepc\.com[/&:?=_]
.admd\.yam\.com[/&:?=_]
.bbs\.gfan\.com/plugin\.php\?id=gfan_viewpic:gfan_adView
.disp\.cc/ads_data/
.pchome\.com\.tw/js/PChomeFS\.js
.so100\.cn/images/a.*\.js
.so100\.cn/images/newshead\.htm
.soaspx\.com/images/hws\.gif
.soaspx\.com/images/iiszj\.gif
.soft4fun\.net/wp-content/themes/arthemia/js/common_footer_min\.js
.subpig\.net/add/
/nrelate-flyout/.*
.check.*\.facebook\.com[/&:?=_]
.d8rk54i4mohrb\.cloudfront\.net/js/slide\.js
.hits\.sinajs\.cn/A1/weiboshare\.html
.plurk\.com/getWidget[/&:?=_]
.v\.t\.qq\.com/follow/widget\.js
.blogger\.com/navbar\.g[/&:?=_]
.pstatic\.xunlei\.com/js/webThunderDetect\.js
.s\.pixfs\.net/common/toolbar/
.s\.pixfs\.net[/&:?=_].*related
.ufile\.qushimeiti\.com/Flashget_union\.php\?
.vlog\.xuite\.net/_a/
.wpa\.qq\.com/pa\?
.x\.soso\.com/js
.adgeo\.163\.com[/&:?=_]
.g\.163\.com/.*&affiliate=
.img1\.126\.net[/&:?=_]
.img2\.126\.net[/&:?=_]
.popme\.163\.com[/&:?=_]
.stat\.ws\.126\.net[/&:?=_]
.a\.youdao\.com[/&:?=_]
.impservice.*\.youdao\.com[/&:?=_]
.youdao\.com/ctlog\?
.youdao\.com/tl\?
.17173\.com/new/
.js\.17173\.com/ping\.js
.178\.com/glr\.js
.market\.178\.com[/&:?=_]
.tuiguang\.178\.com[/&:?=_]
.h\.qhimg\.com/js/iwt-hao360\.js
.h1\.qhimg\.com/js/monitor-v1\.1\.1\.min\.js
.hao\.360\.cn/css/monitorscript\.js
.s\.360\.cn[/&:?=_]
.s\.so\.360\.cn[/&:?=_]
.tf\.360\.cn[/&:?=_]
.sstat\.jd\.com/scslog\?
.56\.com/cfstat/
.56\.com/flashApp/ctrl_ui_site/pause_ad_panel/
.56\.com/js/promo/
.stat\.56\.com[/&:?=_]
.v-56\.com[/&:?=_]
.6\.cn/mdfor/index_new\.js
.6\.cn/mdfor/watch_new11\.js
.r\.6\.cn/imges/watchad/
.r\.6\.cn/sell/
.shrek\.6\.cn[/&:?=_]
.static\.acfun\.tv/json/addata\.json
.bmp\.ali213\.net/js/
.bmp1\.ali213\.net/js/
.bmp1\.ali213\.net/pubjs/
.kcart\.alipay\.com/web/bi\.do\?
.a\.tbcdn\.cn/s/ac\.js
.a\.tbcdn\.cn/s/atp\.js
.a\.tbcdn\.cn/s/tb-tracer-min\.js
.acookie\..*\.gif\?
.music\.baidu\.com/static/html/cbjs\.html
.news\.baidu\.com/nocache/mp/b\.jpg
.play\.baidu\.com/player/static/audio/10s\.mp3
.pos\.baidu\.com[/&:?=_]
.wenku\.baidu\.com/static/common/tmp/red_packet/no1\.swf
hao123img\.com/res/ecom/
.dq\.baidu\.com/nocipher\?
.cb\.baidu\.com[/&:?=_]
.cbjs\.baidu\.com[/&:?=_]
.cpro\.baidu\.com[/&:?=_]
.cpro\.baidustatic\.com[/&:?=_]
.drmcmm\.baidu\.com[/&:?=_]
.duiwai\.baidu\.com[/&:?=_]
.eiv\.baidu\.com[/&:?=_]
.spcode\.baidu\.com[/&:?=_]
.ubmcmm\.baidustatic\.com[/&:?=_]
.iqiyi\.com/player/cupid/.*/pageer\.swf
.msg\.iqiyi\.com[/&:?=_]
.bilibili\.tv/ad/
.btscg\.com/cdn-cgi/nexp/.*/cloudflare/rocket\.js
.union\.china\.com\.cn[/&:?=_]
.act\.chinatimes\.com/aimg/
.cache\.chinatimes\.com/Scripts/bennerad\.min\.js
.chinatimes\.com/ads/
.csdn\.net/ggmm/
.iteye\.com/iframe_ggbd/
.doubleclick\.tv002\.com[/&:?=_]
.douban\.com[/&:?=_].*/fm_bgad\.js
.img3\.douban\.com/js/packed_ad
.discuz\.gtimg\.cn/cloud/scripts/discuz_tips\.js
.n2\.hk/groupon/
.networld\.hk/ad2/
.by\.tel\.cdndm\.com[/&:?=_]
.duowan\.com/duowan\.js
.market\.duowan\.com[/&:?=_]
.msg\.ettoday\.net[/&:?=_]
.fankudo\.com/3C\.html
.js\.a\.focus\.cn/.*_ad/
.simg\.f\.itc\.cn/common/egou/images/
.src\.focus\.cn/common/js/adm2012\.js
.adk\.funshion\.com[/&:?=_]
.adm\.funshion\.com[/&:?=_]
.vas\.funshion\.com[/&:?=_]
.gamersky\.com/img/
.gamersky\.com/piaofu.*/
.gamme\.com\.tw/ga/
/att_count\.js
.hxjs\.tool\.hexun\.com[/&:?=_]
.img\.hexun\.com[/&:?=_].*finalpage.*\.js
.itv\.hexun\.com[/&:?=_]
.blog\.xuite\.net/_public/js/ysmad\.js
.hiad\.myweb\.hinet\.net[/&:?=_]
.hichannel\.hinet\.net/player/radio/hinetAd\.js
.hichannel\.hinet\.net/videoad2/
.p4u\.hinet\.net[/&:?=_]
.p8u\.hinet\.net[/&:?=_]
.town\.xuite\.net/_ad/
.huanqiu\.com/script/HuanQiuAllBottom\.Js
.goto\.www\.iciba\.com[/&:?=_]
.iciba\.com/web/co/ci/
/ifengRotatorAd\.js
.de\.deliver\.ifeng\.com[/&:?=_]
.games\.ifeng\.com/webgame/
.ifeng\.com/ssi-incs/
.ifeng\.com/statics/comment_baidu\.html
.ifengimg\.com/ifeng/ad/
.ifengimg\.com/ifeng/sources/
.ifengimg\.com/mappa/
.ifengimg\.com[/&:?=_].*/rdn_.*\.js
.img\.ifeng\.com/tres/html/
.img\.ifeng\.com/tres/ifeng/
.img\.ifeng\.com/tres/market/
.play\.ifeng\.com/resource_new/js/playbox\.js
.web\.kuaipan\.cn/static/images/anods/
.download\.it168\.com/jscript/bubble\.js
.imanke\.com/static/imanke/pigbbs\.js
.jumpcn\.com/javascript/tshow\.js
.jumpcn\.com/show/
.jdstatic\.tankr\.net/ajax/125\.js
.jdstatic\.tankr\.net/ajax/banner\.js
.a\.ikafan\.com/2/b\.js
.a\.ikafan\.com/3/
.a\.ikafan\.com/4/tengyou\.gif
.bt\.ktxp\.com/iframe/statistics\.js
.kkkmh\.com/iframe/
.ktxp\.com/javascripts/nmjui/
/kocpc\.myweb\.hinet\.net/.*
.pimg\.tw/kocpc/
.st\.vq\.ku6\.cn[/&:?=_]
.dc\.letv\.com[/&:?=_]
.player\.letvcdn\.com[/&:?=_].*\.swf\?
.pro\.hoye\.letv\.com[/&:?=_]
.promotion\.msn\.com\.tw[/&:?=_]
.imgpub\.mop\.com[/&:?=_]
.mopimg\.cn/dc/
.mopimg\.cn/tj/
.pub\.mop\.com[/&:?=_]
.task\.mop\.com/mop_treasure\.jsp
.11\.mydrivers\.com/drivers/
.11\.mydrivers\.com/news/03\.js
.11\.mydrivers\.com/news/google468x60\.js
.11\.mydrivers\.com/myfiles/04\.js
.11\.mydrivers\.com/myfiles/myfiles100.*\.js
/newhuagg/.*_right
/newhuagg/index_
/newhuagg/news_top\.js
.twimg\.edgesuite\.net/appledaily/images/js/OneAD_Article_Video_v1\.js
.bbs\.pcbeta\.com/static/image/biz/
.acount\.pconline\.com\.cn[/&:?=_]
.pcgames\.com\.cn/g/
.pconline\.com\.cn/download/.*/intf.*\.js
.pconline\.com\.cn/js/ivy\.js
/blog/addvisit[/&:?=_]
.7headlines\.com/sticker
.ad\.pixnet\.net[/&:?=_]
.api\.pixnet\.tv/count[/&:?=_]
.counter\.pixplug\.in/count\.php
.error\.pixplug\.in[/&:?=_]
.pixfs\.net[/&:?=_].*/mib
.pixgold\.com[/&:?=_]
.referer\.pixplug\.in[/&:?=_]
.banana\.plurk\.com[/&:?=_]
.trex\.plurk\.com[/&:?=_]
.de\.as\.pptv\.com[/&:?=_]
.s1\.pplive\.cn/sta\.js
.synacast\.com[/&:?=_]
.web\.data\.pplive\.com[/&:?=_]
.aa\.sdo\.com[/&:?=_]
.aagw\.sdo\.com[/&:?=_]
.adrs\.sdo\.com[/&:?=_]
.ck\.sdo\.com[/&:?=_]
.sy\.sdo\.com[/&:?=_]
.c\.pingba\.qidian\.com/increase\.htm
.login\.sdo\.com/sdo/PRes/js/sdo_beacon\.js
.qdmm\.com/javascript/NewSNDAPop\.js
.qidian\.com/javascript/abc\.htm
.qidian\.com/Javascript/DoublePop\.js
.qidian\.com/Javascript/NewSNDAPop\.js
.qidian\.com/javascript/SNDAADAltern\.js
.script\.cmfu\.com/ADScript/
.sdo\.com/\?method=GetAd&
.l\.qq\.com/p\?
.promreport\.crm2\.qq\.com/wpadisplay/r\.gif\?
.qq\.com/livemsg\?
.ra\.gtimg\.com/adsame/
.wa\.gtimg\.com[/&:?=_]
.tajs\.qq\.com[/&:?=_]
.tcss\.qq\.com[/&:?=_]
.gdt\.qq\.com[/&:?=_]
.isdspeed\.qq\.com[/&:?=_]
.users\.qzone\.qq\.com/cgi-bin/pos/cgi_getpos\?
.ebp\.renren\.com[/&:?=_]
.shaft\.jebe\.renren\.com[/&:?=_]
.sina\.com/assets/js/dart/
.sina\.com/rm/
.bj\.house\.sina\.com\.cn/iframe/
.log\.interest\.mix\.sina\.com\.cn[/&:?=_]
.news\.sina\.com\.cn/js/792/.*head.*\.js
.news\.sina\.com\.cn/pvcounter/
.pfp\.sina\.com\.cn/jczs\.html
.rs\.sinajs\.cn[/&:?=_]
.sina\.com\.cn/litong/
.sinaimg\.cn/unipro/
.simg\.sinajs\.cn/blog7style/images/special/
.mail\.sina\.com\.cn/admail/
.mail\.sina\.com\.cn/freemail/news/oneline-notice\.html
.p4p\.sina\.com\.cn[/&:?=_]
.dcads\.sina\.com\.cn[/&:?=_]
.video\.sina\.com\.cn/iframe/
.biz\.weibo\.com[/&:?=_]
.as\.sinahk\.net[/&:?=_]
.buy\.sina\.com\.tw/js/sina_popup\.php
.ezprice\.com\.tw/partner/sina/ez2sina\.js
.news\.sina\.com\.tw/_data/adsbro_hotspot\.js
.news\.sina\.com\.tw/js/ti\.js
.images\.sohu\.com/bill/
.images\.sohu\.com/cs/
.itc\.cn[/&:?=_].*/tracker\.js
.news\.sohu\.com/upload/article/2012/images/swf/
.txt\.go\.sohu\.com/ip/soip
.xls\.go\.sohu\.com[/&:?=_]
.z\.t\.sohu\.com[/&:?=_]
.images\.sohu\.com/ytv/.*\.swf
.vm\.aty\.sohu\.com[/&:?=_]
.brand\.sogou\.com[/&:?=_]
.file\.cloud\.sogou\.com/.*/superzone/
.sogou\.com/js/pb_.*\.js
.wan\.sogou\.com/pop/
.img\.solidot\.com\.cn[/&:?=_]
.pv\.zdnet\.com\.cn[/&:?=_]
.8.*\.tianya\.cn[/&:?=_]
.blog\.tianya\.cn/tuijian/tanchu\.js
.click\.tianyaui\.com[/&:?=_]
.global\.tianyaui\.com/global/wizard/js/wizard\.js
.static\.tianyaui\.com[/&:?=_].*/stat_20080313\.js
.wres\.mangocity\.com/js/w/hezuo/
.event\.udn\.com[/&:?=_]
.member\.udn\.com/NEWS/MISC/
.udn\.com/1024/NEWS/INCLUDE/
.udn\.com/adpinline/
.udn\.com/images/forumimg/digad\.html
.udn\.com/NEWS/watermark_omo_2010\.js
.udn\.com[/&:?=_].*/ad/
.udn\.com[/&:?=_].*/bd/
.sp\.vcimg\.com[/&:?=_]
.aoodoo\.weiphone\.com[/&:?=_]
.lab\.weiphone\.com/images_new/ad-
.weiphone\.com/baidu\.html
.xinhuanet\.com/classad/
.xinhuanet\.com[/&:?=_].*/ad_
.analytics-union\.sandai\.net[/&:?=_]
.analytics-union\.xunlei\.com[/&:?=_]
.biz.*\.sandai\.net[/&:?=_]
.img\.kuai\.xunlei\.com/img/v2/fen/
.img\.kuai\.xunlei\.com/js/statistics\.js
.js\.kankan\.xunlei\.com/5\.2/mp4/js/kankan_commercial_mp4_563\.js
.kkpgv2\.xunlei\.com[/&:?=_]
.record\.kuai\.xunlei\.com[/&:?=_]
.l\.yimg\.com/d/lib/bc/bcr_2\.0\.5\.js
.l\.yimg\.com/pq/
.s\.yimg\.com/gs/apex/
.s\.yimg\.com/ja/ap/tw/js/
.tw\.dictionary\.search\.yahoo\.com/beacon/
.tw\.img\.webmaster\.yahoo\.com[/&:?=_].*/ystats\.gif
.tw\.yimg\.com/a/tw/
.yimg\.com/.*/ysm/
.l\.yimg\.com/mq/hk/promotions/
.s1\.josho\.yamedia\.tw/f/plugin\.swf[/&:?=_]
.atm\.youku\.com[/&:?=_]
.hz\.youku\.com/red/
.l\.ykimg\.com[/&:?=_]
.static\.youku\.com/.*/index/js/iresearch\.js
.static\.youku\.com/.*/js/cps\.js
.player\.pb\.ops\.tudou\.com/info\.php\?
.tudou\.com[/&:?=_].*/outside\.php
.yzdb\.tv/ad/
.copy\.ousns\.com[/&:?=_]
.res\.yyets\.com/ads/
.yyets\.com/public/rooms
.ca\.cbsi\.com\.cn/rpv\?
.icon\.zol-img\.com\.cn/mainpage/js/click\.js
.icon\.zol-img\.com\.cn/public/js/web_foot\.js
.imp\.zol\.com\.cn[/&:?=_]
.p\.zol-img\.com\.cn[/&:?=_]
.pc3w\.com/js/
{ +filter{chinalist-lite} }
*
{ -block }
.vdisk\.cn/img/loading\.gif
/configs/article/bottom\.js
/configs/article/pagebottom\.js
/configs/article/pagetop\.js
.77119\.com/js/fenxiang\.js
.dukankan\.com/xiaoyi/js/Footer\.js
.dukankan\.com/xiaoyi/js/header\.js
.dukankan\.com/xiaoyi/js/loginTop\.js
.jj\.5ccc\.net/scripts/new/pagetop\.js
.shanwen\.com/configs/article/pagetop3\.js
.wcxiaoshuo\.com/js/big5\.js
.wcxiaoshuo\.com/js/default\.js
.wcxiaoshuo\.com/js/index\.js
.pole\.6rooms\.com/adpolestar/.*_qtie\.swf
.ali213\.net/.*/pop\.js
.ali213\.net/.*/tj\.js
.interface\.bilibili\.tv/ad/topic
.q\.funshion\.com/js\.php
.player\.letvcdn\.com/p/.*/newplayer/LetvPlayer\.swf
.player\.letvcdn\.com/p/.*/newplayer/LivePlayer\.swf
.onlinedown\.net/newhuagg/sort_pic_24_24\.js
.video\.appledaily\.com\.hk/admedia/
.ad1\.nownews\.com/ads\.php\?ownerid=1294
.ad1\.nownews\.com/ads\.php\?ownerid=1355
.sinaimg\.cn[/&:?=_].*/deco/.*/sinaObj\.js
.xinhuanet\.com/static/rmedia/pv\.swf
.l\.yimg\.com/f/a/tw/.*/790840_.*\.swf
.l\.yimg\.com/f/a/tw/elephant/.*240x94.*\.swf
.union\.maccms\.com/gg/baidu\.html
.union\.maccms\.com/gg/qvod\.html
.union\.maccms\.com/player8/init\.js
{ -block +handle-as-image }
/data/preview/.*
.vdisk\.cn/img/logo
.adimg\.adtpl\.jd\.com/uploads/
.static\.hdslb\.com/ad-images/
/common/cf/.*\.thumb
.hinet\.net/.*bien.*/
.hd\.duba\.net/vip\.ijinshan\.com/repository/ad-images/
.ads\.yimg\.com/ja/a/
/adbanner/.*
